#!/bin/bash

#read -p "Enter a number for multiplication table: " num
num=2
i=1
while [ $i -le 10 ]; do
	echo "$num * $i = $((num*i))"
	(( i++))
done
 
i=1
until [ $i -gt 10 ]; do
	echo "$num * $i = $((num*i))"
	(( i++ ))
done
